# Generated by Django 5.1.7 on 2025-03-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0002_alter_housing_address_alter_refugee_user_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='ngo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing_listings', to='refugees.ngo'),
        ),
        migrations.AddField(
            model_name='job',
            name='ngo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='refugees.ngo'),
        ),
    ]
